### ISSUE TITLE
Would it be possible for you to set up a GitHub sponsorship

### ISSUE THREAD

**Issue by hanaral** [thaytan/OpenHMD#14]
Hello, I've been following this project for a while and I understand that you are doing this in your free time. I was wondering if you would be able to set up a GitHub sponsor so I can help fund this awesome project!

**Comment by thaytan** [comment]
Wow! I appreciate the encouragement. I'll look into it.

**Comment by thaytan** [comment]
I have set up a sponsor profile at https://github.com/sponsors/thaytan
