### ISSUE TITLE
Are there plans to further develop this project or has all development gone to monado?

### ISSUE THREAD

**Issue by Mookeydude** [thaytan/OpenHMD#51]
Is this project still being worked on or is rift s driver development being predominantly done in monado now?

**Comment by thaytan** [comment]
I'm only working in Monado. I plan to move the CV1 driver to a native Monado driver at some point. It is the much more active project and providing a full OpenXR runtime with a standard API is (IMO) more valuable

**Comment by Mookeydude** [comment]
Ok, thanks for answering!
